config/routes.rb
Qp::Application.routes.draw do

  root "coupons#index"

  post "user/session_for_mobile" => "user#session_for_mobile", as: :session_for_mobile

  devise_for :admins
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" } 

  get "brands/index" => "brands#index", as: :brands_index
  devise_for :brands, controllers: { registrations: "brands/registrations", sessions: "brands/sessions" }, path_prefix: "my"
  resources :brands

  get 'categories/index' => "categories#index", as: :categories_index
  get 'categories/show/:id' => "categories#show", as: :category_show
  post 'categories/create' => "categories#create", as: :category_create
  post 'categories/update' => "categories#update", as: :category_update
  get 'categories/destroy/:id' => "categories#destroy", as: :category_destroy

  post 'sub_categories/create' => "sub_categories#create", as: :sub_categories_create
  post 'sub_categories/update' => "sub_categories#update", as: :sub_categories_update
  get 'sub_categories/destroy/:id' => "sub_categories#destroy", as: :sub_categories_destroy

  get "cities/index" => "cities#index", as: :cities_index
  get 'cities/show/:id' => "cities#show", as: :cities_show
  post 'cities/create' => "cities#create", as: :cities_create
  post 'cities/update' => "cities#update", as: :cities_update
  get 'cities/destroy/:id' => "cities#destroy", as: :cities_destroy
  post 'cities/search_districts_for_city' => "cities#search_districts_for_city", as: :search_districts_for_city

  post 'districts/create' => "districts#create", as: :districts_create
  post 'districts/update' => "districts#update", as: :districts_update
  get 'districts/destroy/:id' => "districts#destroy", as: :districts_destroy

  get 'coupons/history' => "coupons#history", as: :coupons_history
  get 'coupons/published_coupons/:id' => "coupons#published_coupons", as: :coupons_published
  get 'coupons/category/:id' => "coupons#by_category", as: :coupons_by_category
  get 'coupons/sub_category/:id' => "coupons#by_sub_category", as: :coupons_by_sub_category
  get 'coupons/saved_coupons/:id' => "coupons#saved_coupons", as: :saved_coupons
  get 'coupons/pending_coupons/:id' => "coupons#pending_coupons_by_brand", as: :pending_coupons_by_brand
  get 'coupons/pending_coupons' => "coupons#pending_coupons", as: :pending_coupons
  get 'coupons/valid_coupons' => "coupons#valid_coupons", as: :valid_coupons
  get 'coupons/favorites' => "coupons#favorites", as: :favorite_coupons
  post 'coupons/mark_favorite' => "coupons#mark_favorite", as: :mark_favorite
  post 'coupons/approve_coupon/:id' => "coupons#approve_coupon", as: :approve_coupon
  resources :coupons

  get "coupon_states/index" => "coupon_states#index", as: :coupon_states_index
  post "coupon_states/create" => "coupon_states#create", as: :coupon_states_create
  get "coupon_states/destroy/:id" => "coupon_states#destroy", as: :coupon_states_destroy
  post "coupon_states/update" => "coupon_states#update", as: :coupon_states_update

  get "coupon_types/index" => "coupon_types#index", as: :coupon_types_index
  post "coupon_types/create" => "coupon_types#create", as: :coupon_types_create
  get "coupon_types/destroy/:id" => "coupon_types#destroy", as: :coupon_types_destroy
  post "coupon_types/update" => "coupon_types#update", as: :coupon_types_update

  get "branches/index/:id" => "branches#index", as: :branches_index
  post "branches/create" => "branches#create", as: :create_branch
  get "branches/destroy/:id" => "branches#destroy", as: :destroy_branch
  post "branches/edit" => "branches#edit", as: :edit_branch
  post "branches/grouped_branches" => "branches#grouped_branches", as: :grouped_branches
  post "branches/branches_in_district" => "branches#branches_in_district"

  

end

app/models/branch.rb
class Branch < ActiveRecord::Base

	belongs_to :district
	belongs_to :brand
	
	has_many :availabilities, dependent: :destroy
	has_many :coupons, through: :availabilities

end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController

  def index
    @brand = Brand.find(params[:id])
  	@branches = Branch.where(brand_id: params[:id])
  end

  def create

  	@branch = Branch.new
  	@branch.brand = Brand.find(params[:brand_id])
    @branch.name = params[:name]
  	@branch.address = params[:address]
  	@branch.reference = params[:reference]
  	@branch.start_hour = params[:start_hour]
  	@branch.start_minute = params[:start_minute]
  	@branch.end_hour = params[:end_hour]
  	@branch.end_minute = params[:end_minute]
  	@branch.has_parking = params[:has_parking] == "1" ? true : false
  	@branch.has_valet = params[:has_valet] == "1" ? true : false
  	@branch.latitude = params[:latitude]
  	@branch.longitude = params[:longitude]
  	@branch.altitude = params[:altitude]
  	@branch.district_id = params[:district_id]
  	@branch.save
    
  	respond_to do |format|
		  format.js
  	end
  end

  def destroy
    @branch = Branch.find(params[:id])
    @branch.destroy
    respond_to do |format|
      format.js
    end
  end

  def edit
    @branch = Branch.find(params[:branch_id])
    @branch.brand = Brand.find(params[:brand_id])
    @branch.name = params[:edit_name]
    @branch.address = params[:edit_address]
    @branch.reference = params[:edit_reference]
    @branch.start_hour = params[:edit_start_hour]
    @branch.start_minute = params[:edit_start_minute]
    @branch.end_hour = params[:edit_end_hour]
    @branch.end_minute = params[:edit_end_minute]
    @branch.has_parking = (params[:edit_has_parking] == "1") ? true : false
    @branch.has_valet = (params[:edit_has_valet] == "1") ? true : false
    @branch.latitude = params[:edit_latitude]
    @branch.longitude = params[:edit_longitude]
    @branch.altitude = params[:edit_altitude]
    @branch.district_id = params[:edit_district_id]

    @branch.save
    respond_to do |format|
      format.js
    end

  end

  def grouped_branches

    @brand = Brand.find(params[:brand_id])
    @branches = @brand.branches

    @coupon = (params[:c_id].nil? || params[:c_id].empty?) ? Coupon.new : Coupon.find(params[:c_id])

    respond_to do |format|
      format.js
    end
  end

  def branches_in_district
    @brand = Brand.find(params[:brand_id])
    @branches = @brand.branches.where(district_id: params[:district_id])
    @coupon = (params[:coupon_id] == "-1") ? Coupon.new : Coupon.find(params[:coupon_id])
    respond_to do |format|
      format.js
    end
  end
end

app/helpers/branches_helper.rb
module BranchesHelper

	def attention_time(time_of_day)
		hour_options = ""
		24.times do |i|
			hour_options = hour_options + "<option value=\"#{i}\">#{i}</option>"
		end
		minutes_options = ""
		12.times do |i|
			minutes_options = minutes_options + "<option value=\"#{i*5}\">#{i*5}</option>"
		end
		selects = (select_tag "#{time_of_day}_hour", hour_options.html_safe, class: "small-select") + (select_tag "#{time_of_day}_minute", minutes_options.html_safe, class: "small-select")
	end
end

app/views/branches/_branch_index_item.html.haml
.accordion-group
	.accordion-heading
		=link_to "#branch_#{br.id}", class: "accordion-toggle", data: {toggle: "collapse", parent: "#accordion2", id: "#{br.id}"} do
			%i.icon-bookmark
			= "Tienda #{index} - #{br.address} - #{br.id}"
	.accordion-body.collapse{ id: "branch_#{br.id}"}
		.accordion-inner
			%ul
				%li
					%span
						Nombre: 
					%span{class: "name no_style"}
						= br.name
				%li
					%span
						Dirección: 
					%span{class: "address no_style"}
						= br.address
				%li
					%span
						Referencia:
					%span{class: "reference no_style"}
						= br.reference
				%li
					%span
						Tiene estacionamiento: 
					%span{class: "parking  no_style"}
						= br.has_parking ? "Si" : "No"
				%li
					%span
						Tiene valet parking:
					%span{class: "valet no_style"}
						= br.has_valet ? "Si" : "No"
				%li
					%span
						Horario de atención:
					%span{class: "hours no_style"}
						= "#{br.start_hour}:#{br.start_minute} am - #{br.end_hour}:#{br.end_minute} pm"
					=hidden_field_tag "to_edit_start_hour", br.start_hour
					=hidden_field_tag "to_edit_start_minute", br.start_minute
					=hidden_field_tag "to_edit_end_hour", br.end_hour
					=hidden_field_tag "to_edit_end_minute", br.end_minute
				%li
					%span
						Distrito:
					%span{class: "district no_style", data: {id: "#{br.district_id}"}}
						= br.district.name
				%li
					%span
						Ciudad:
					%span{class: "city no_style", data: {id: "#{br.district.city.id}"}}
						= br.district.city.name
				%li
					%span
						Latitud:
					%span{class: "latitude no_style"}
						= br.latitude
				%li
					%span
						Longitud:
					%span{class: "longitude no_style"}
						= br.longitude
				%li
					%span
						Altitud:
					%span{class: "altitude no_style"}
						= br.altitude
			.branch_options
				=link_to "Editar", "#edit_branch", class: "btn click_to_edit_branch", role: "button", data: {toggle: "modal"}
				=link_to "Eliminar", destroy_branch_path(br.id), remote: true, class: "btn btn-danger"

app/views/branches/branches_in_district.js.haml
- if @branches.count > 0 
	$(".branches_in_district").html("#{j render 'coupons/branches_item', branches: @branches, coupon: @coupon}");
- else
	$(".branches_in_district").html("<h2>No existen tiendas para este distrito</h2>");

app/views/branches/create.js.haml
$("#close_button").click();
$("#create_new_branch")[0].reset();
$("#accordion2").append("#{j render 'branch_index_item', br: @branch, index: @branch.brand.branches.count}");

app/views/branches/destroy.js.haml
$("#branch_#{@branch.id}").parents(".accordion-group").remove();

app/views/branches/edit.js.haml
//$(".close").click();
//$(".to_change").replaceWith("#{j render 'branch_index_item', br: @branch, index: 0}");
window.location.reload();

app/views/branches/grouped_branches.js.haml
-if @branches.count>0
	$("#replaceable_branches").html("#{j render 'coupons/branches_item', branches: @branches, coupon: @coupon}");
-else
	$("#replaceable_branches").html("#{j link_to 'Esta marca no registra tiendas, por favor crea una para continuar', branches_index_path(@brand.id)}");

app/views/branches/index.html.haml
.page_container
	= render "brands/everywhere_logo", current_brand: current_brand, message: "Indice de tiendas"
	%h1 
		-if admin_signed_in?
			= (@brand.name.nil? || @brand.name.empty?) ? "Nombre de tienda no registrado" : @brand.name
		-else
			= current_brand.name

	#accordion2.accordion
		- @branches.each.with_index(1) do |br, index|
			=render "branch_index_item", br: br, index: index

	#new_branch_for_this_brand
		=link_to "Registrar nueva tienda", "#myModal", role: "button", class: "btn btn-primary", data: {toggle: "modal"}
		=form_tag create_branch_path, :remote => true, id: "create_new_branch" do
			#myModal.modal.hide.fade{ tabindex: "-1", role: "dialog", aria: {labelledby: "myModalLabel", hidden: "true"}}
				.modal-header
					%button{ type: "button", class: "close", data: {dismiss: "modal"},aria:{hidden: "true"}}
						×
					%h3#myModalLabel
						Registrar nueva tienda
				.modal-body
					-if admin_signed_in?
						=hidden_field_tag "brand_id", @brand.id
					-else
						=hidden_field_tag "brand_id", current_brand.id
					=hidden_field_tag "longitude"
					=hidden_field_tag "altitude"
					=hidden_field_tag "latitude"	
					.new_branch_part
						= label_tag "name", "Nombre: "
						= text_field_tag "name"
					.new_branch_part
						= label_tag "address", "Dirección: "
						= text_field_tag "address", "",class: "to_search_in_maps"
					.new_branch_part
						= label_tag "reference", "Referencia: "
						= text_area_tag "reference"
					.new_branch_part
						= label_tag "start_time", "Hora de Atencion: "
						= attention_time :start 
						%span#separator_dash -
						= attention_time :end
					.new_branch_part
						= label_tag "has_parking","¿Tiene estacionamiento?"
						= boolean_select "has_parking"
					.new_branch_part
						= label_tag "has_valet","¿Tiene valet parking? "
						= boolean_select "has_valet"
					.new_branch_part
						=label_tag "city", "Ciudad: "
						= select_tag "city", options_from_collection_for_select(City.all, :id, :name), prompt: "Elige una ciudad"
					.new_branch_part
						=label_tag "district_id", "Distrito: "
						= select_tag "district_id",option_groups_from_collection_for_select(City.all, :districts, :name, :id, :name), prompt: "Elige un distrito"
					#map_container
						%span
							¿Dónde se encuentra ubicada la tienda?
						#map_canvas
				.modal-footer
					%button#close_button.btn{data: {dismiss: "modal"}, aria: {hidden: "true"}}
						Cancelar
					=submit_tag "Guardar", class: "btn btn-primary"

	#edit_branch_for_this_brand
		=form_tag edit_branch_path, :remote => true, id: "edit_this_branch" do
			#edit_branch.modal.hide.fade{ tabindex: "-1", role: "dialog", aria: {labelledby: "myModalLabel", hidden: "true"}}
				.modal-header
					%button{ type: "button", class: "close", data: {dismiss: "modal"},aria:{hidden: "true"}}
						×
					%h3#myModalLabel
						Editar registro de tienda
				.modal-body
					-if admin_signed_in?
						=hidden_field_tag "brand_id", @brand.id
					-else
						=hidden_field_tag "brand_id", current_brand.id
					=hidden_field_tag "branch_id", value: -1
					=hidden_field_tag "edit_longitude"
					=hidden_field_tag "edit_altitude"
					=hidden_field_tag "edit_latitude"
					.new_branch_part
						= label_tag "edit_name", "Nombre: "
						= text_field_tag "edit_name"
					.new_branch_part
						= label_tag "edit_address", "Dirección: "
						= text_field_tag "edit_address", "",class: "to_search_in_maps"
					.new_branch_part
						= label_tag "edit_reference", "Referencia: "
						= text_area_tag "edit_reference"
					.new_branch_part
						= label_tag "edit_time", "Hora de Atencion: "
						= attention_time :edit_start 
						%span#separator_dash -
						= attention_time :edit_end
					.new_branch_part
						= label_tag "edit_has_parking","¿Tiene estacionamiento?"
						= boolean_select "edit_has_parking"
					.new_branch_part
						= label_tag "edit_has_valet","¿Tiene valet parking? "
						= boolean_select "edit_has_valet"
					.new_branch_part
						=label_tag "edit_city", "Ciudad: "
						= select_tag "edit_city", options_from_collection_for_select(City.all, :id, :name)
					.new_branch_part
						=label_tag "edit_district_id", "Ciudad: "
						= select_tag "edit_district_id",option_groups_from_collection_for_select(City.all, :districts, :name, :id, :name)
					#map_container_edit
						%span
							¿Dónde se encuentra ubicada la tienda?
						#map_canvas_edit
				.modal-footer
					%button#close_button.btn{data: {dismiss: "modal"}, aria: {hidden: "true"}}
						Cancelar
					=button_tag "Listo", class: "btn btn-primary"

		- content_for :ready_scripts do
			:javascript
				$(document).ready(function(){
					var map = new GMaps({
						div: "#map_canvas",
						lat: -12.043333,
						lng: -77.028333,
						click: function(e){
							map.removeMarkers();
							map.addMarker({
							lat: e.latLng.lat(),
							lng: e.latLng.lng()
						});
						$("#longitude").val(e.latLng.lng());
						$("#latitude").val(e.latLng.lat());
						}
					});

					$("#map_canvas").attr("style","width: 100%; height: 350px;");

					$("#new_branch_for_this_brand").on("shown", function(){
						map.refresh();
					});

					$(".accordion-group").click(function(){
						var latitude = parseFloat($(this).find(".latitude").text().trim())
						var longitude = parseFloat($(this).find(".longitude").text().trim())

						var edit_map = new GMaps({
							div: "#map_canvas_edit",
							lat: latitude,
							lng: longitude,
							click: function(e){
								edit_map.removeMarkers();
								edit_map.addMarker({
									lat: e.latLng.lat(),
									lng: e.latLng.lng()
								});
								$("#edit_longitude").val(e.latLng.lng());
								$("#edit_latitude").val(e.latLng.lat());
							}
						});

						edit_map.addMarker({
							lat: latitude,
							lng: longitude
						});

						$("#edit_branch_for_this_brand").on("shown", function(){
							edit_map.refresh();
							edit_map.setCenter(latitude, longitude, function(){});
						});

						$("#map_canvas_edit").attr("style","width: 100%; height: 350px;");
					});

					$("#district_id").change(function(){
						var value = $(this).find("option:selected").text();
						var city_name = $("#city option:selected").text();
						$.ajax({
							method: "GET",
							url: "https://maps.googleapis.com/maps/api/geocode/json?address="+value+","+city_name+"&sensor=false",
							success: function(data){
								var results = data.results;
								var lat_from_search = results[0].geometry.location.lat;
								var lng_from_search = results[0].geometry.location.lng;
								map.setCenter(lat_from_search, lng_from_search, function(){});
							}
						});
					});

					$("#edit_district_id").change(function(){
						var value = $(this).find("option:selected").text();
						var city_name = $("#edit_city option:selected").text();
						$.ajax({
							method: "GET",
							url: "https://maps.googleapis.com/maps/api/geocode/json?address="+value+","+city_name+"&sensor=false",
							success: function(data){
								var results = data.results;
								var lat_from_search = results[0].geometry.location.lat;
								var lng_from_search = results[0].geometry.location.lng;
								map.setCenter(lat_from_search, lng_from_search, function(){});
							}
						});
					});
				});