config/routes.rb
Qp::Application.routes.draw do

  root "coupons#index"

  post "user/session_for_mobile" => "user#session_for_mobile", as: :session_for_mobile

  devise_for :admins
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" } 

  get "brands/index" => "brands#index", as: :brands_index
  devise_for :brands, controllers: { registrations: "brands/registrations", sessions: "brands/sessions" }, path_prefix: "my"
  resources :brands

  get 'categories/index' => "categories#index", as: :categories_index
  get 'categories/show/:id' => "categories#show", as: :category_show
  post 'categories/create' => "categories#create", as: :category_create
  post 'categories/update' => "categories#update", as: :category_update
  get 'categories/destroy/:id' => "categories#destroy", as: :category_destroy

  post 'sub_categories/create' => "sub_categories#create", as: :sub_categories_create
  post 'sub_categories/update' => "sub_categories#update", as: :sub_categories_update
  get 'sub_categories/destroy/:id' => "sub_categories#destroy", as: :sub_categories_destroy

  get "cities/index" => "cities#index", as: :cities_index
  get 'cities/show/:id' => "cities#show", as: :cities_show
  post 'cities/create' => "cities#create", as: :cities_create
  post 'cities/update' => "cities#update", as: :cities_update
  get 'cities/destroy/:id' => "cities#destroy", as: :cities_destroy
  post 'cities/search_districts_for_city' => "cities#search_districts_for_city", as: :search_districts_for_city

  post 'districts/create' => "districts#create", as: :districts_create
  post 'districts/update' => "districts#update", as: :districts_update
  get 'districts/destroy/:id' => "districts#destroy", as: :districts_destroy

  get 'coupons/history' => "coupons#history", as: :coupons_history
  get 'coupons/published_coupons/:id' => "coupons#published_coupons", as: :coupons_published
  get 'coupons/category/:id' => "coupons#by_category", as: :coupons_by_category
  get 'coupons/sub_category/:id' => "coupons#by_sub_category", as: :coupons_by_sub_category
  get 'coupons/saved_coupons/:id' => "coupons#saved_coupons", as: :saved_coupons
  get 'coupons/pending_coupons/:id' => "coupons#pending_coupons_by_brand", as: :pending_coupons_by_brand
  get 'coupons/pending_coupons' => "coupons#pending_coupons", as: :pending_coupons
  get 'coupons/valid_coupons' => "coupons#valid_coupons", as: :valid_coupons
  get 'coupons/favorites' => "coupons#favorites", as: :favorite_coupons
  post 'coupons/mark_favorite' => "coupons#mark_favorite", as: :mark_favorite
  post 'coupons/approve_coupon/:id' => "coupons#approve_coupon", as: :approve_coupon
  resources :coupons

  get "coupon_states/index" => "coupon_states#index", as: :coupon_states_index
  post "coupon_states/create" => "coupon_states#create", as: :coupon_states_create
  get "coupon_states/destroy/:id" => "coupon_states#destroy", as: :coupon_states_destroy
  post "coupon_states/update" => "coupon_states#update", as: :coupon_states_update

  get "coupon_types/index" => "coupon_types#index", as: :coupon_types_index
  post "coupon_types/create" => "coupon_types#create", as: :coupon_types_create
  get "coupon_types/destroy/:id" => "coupon_types#destroy", as: :coupon_types_destroy
  post "coupon_types/update" => "coupon_types#update", as: :coupon_types_update

  get "branches/index/:id" => "branches#index", as: :branches_index
  post "branches/create" => "branches#create", as: :create_branch
  get "branches/destroy/:id" => "branches#destroy", as: :destroy_branch
  post "branches/edit" => "branches#edit", as: :edit_branch
  post "branches/grouped_branches" => "branches#grouped_branches", as: :grouped_branches
  post "branches/branches_in_district" => "branches#branches_in_district"

  

end

app/models/brand.rb
class Brand < ActiveRecord::Base
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise	:database_authenticatable, 
			:registerable,
			:recoverable,
			:rememberable,
			:trackable,
			:validatable

	has_many :categorizations, dependent: :destroy
	has_many :sub_categories, through: :categorizations
	
	has_many :branches, dependent: :destroy

	has_many :coupons, dependent: :destroy

	has_attached_file :logo_image, styles: {
		medium: "150x150>",
		small: "50x50>"
	}, 
	path: ":rails_root/public/system/:class/:attachment/:id/:style/:filename",
	url: "/system/:class/:attachment/:id/:style/:filename"

	def safe_name
		if name.nil? || name.empty?
			"Nombre no registrado"
		else
			name
		end
	end
end

app/models/brands/registrations_controller.rb
class Brands::RegistrationsController < Devise::RegistrationsController

	def sign_up(resource_name, resource)
		if admin_signed_in?
			return
		else
			super
		end
	end

	def after_sign_up_path_for(resource)
		if admin_signed_in?
			redirect_to brands_index_path
		else
			edit_brand_registration_path
		end
	end

end

app/models/brands/sessions_controller.rb
class Brands::SessionsController < Devise::SessionsController

	def create
		super
		if current_brand.name.nil? || current_brand.name.empty?
			set_flash_message :notice, :signed_in_with_incompleted_data
		end		
	end
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController

  before_action :set_brand, only: [:edit, :update]

  def index
  	@brands = Brand.all
  end

  def edit

  end

  def update
  	respond_to do |format|
  		if @brand.update(brand_params)
  			format.html {redirect_to brands_index_path, notice: "Registro actualizado"}
  		else
  			format.html { render action: "edit" }
  		end
  	end
  end

  private

  def set_brand
	@brand = Brand.find(params[:id])
  end

  def brand_params
    params.require(:brand).permit(:name, :email, :fb_link, :tw_link, :logo_image, {:sub_category_ids => []})
  end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/views/brands/_everywhere_logo.html.haml
%h6
	-if brand_signed_in? && current_brand.name?
		#represent_logo
			-if current_brand.logo_image?
				=link_to valid_coupons_path do
					=image_tag current_brand.logo_image.url(:small)
			-if message.empty?
				=link_to "", "#", style: "position: relative; top: 10px;"
			-else 
				=link_to " :: #{message}", "#", style: "position: relative; top: 10px;"

app/views/brands/_form.html.haml
=form_for(@brand) do |f|
  .edit_brand_part
    = f.label :name, "Nombre: "
    = f.text_field :name

  .edit_brand_part
    = f.label :email, "Correo: "
    = f.email_field :email, autofocus: true

  .edit_brand_part.brand_logo
    -if @brand.logo_image?
      =image_tag @brand.logo_image.url(:medium)
    = f.label :logo_image, "Logo: "
    = f.file_field :logo_image

  .edit_brand_part
    = f.label :fb_link, "Perfil de Facebook: "
    = f.text_field :fb_link

  .edit_brand_part
    = f.label :tw_link, "Perfil de Twitter: "
    = f.text_field :tw_link

  .edit_brand_part
    =label_tag "categories_in_edit_brand","Seleccione las categorias en las que quiera participar: "
    =select_tag "categories_in_edit_brand", options_from_collection_for_select(Category.all, :id, :name)
    =hidden_field_tag "brand[sub_category_ids][]", nil
  
  / .edit_brand_part#sub_categories_go_here
  /   - Category.all.each do |category|
  /     .sub_category{id: "category_#{category.id}"}
  /       %ul
  /         - category.sub_categories.each do |sub_category|
  /           %li
  /             =check_box_tag "brand[sub_category_ids][]", sub_category.id, @brand.sub_category_ids.include?(sub_category.id), id: dom_id(sub_category)
  /             =label_tag dom_id(sub_category), sub_category.name, class: "sub_category_checkbox"

  .edit_brand_part#sub_categories_go_here
    - Category.all.each do |category|
      .modal.hide.fade{id:"category_#{category.id}",  tabindex: "-1", role: "dialog", aria: {labelledby: "myModalLabel", hidden: "true"}}
        .modal-header
          %button{ type: "button", class: "close", data: {dismiss: "modal"},aria:{hidden: "true"}}
            ×
          %h3#myModalLabel
            = category.name
        .modal-body
          %ul
            - category.sub_categories.each do |sub_category|
              %li
                =check_box_tag "brand[sub_category_ids][]", sub_category.id, @brand.sub_category_ids.include?(sub_category.id), id: dom_id(sub_category)
                =label_tag dom_id(sub_category), sub_category.name, class: "sub_category_checkbox"
        .model-footer
          .modal-footer
            %button#close_button.btn{data: {dismiss: "modal"}, aria: {hidden: "true"}}
              Cancelar
            =link_to "Actualizar", "#", class: "btn btn-primary categories_choosen"

  .submit_brand_part{ style: "clear: both;" }
    = f.submit "Actualizar datos" 

app/views/brands/edit.html.haml
.page_container
	%h1
		Editar
		= (@brand.name.nil? || @brand.name.empty?) ? "Marca" : @brand.name

	=render "form"

	%ul
		%li
			=link_to "volver", brands_path

app/views/brands/index.html.haml
.page_container
	%h6
		%a{href: "index.html"}
			Tiendas
		\/ indice
	.inner_content
		%h1
			Tiendas registradas
		%table.table.table-striped
			%tr
				%th
					\#
				%th
					Nombre
				%th
					Correo de activacion
				%th
					Numero de Tiendas
				%th
					Opciones
			-@brands.each.with_index(1) do |brand, index|
				%tr
					%td
						=index
					%td
						=brand.name? ? brand.name : "No ingresado"
					%td
						=brand.email
					%td
						=link_to brand.branches.count, branches_index_path(brand.id)
					%td
						=link_to "Editar", edit_brand_path(brand)