config/routes.rb
Qp::Application.routes.draw do

  root "coupons#index"

  post "user/session_for_mobile" => "user#session_for_mobile", as: :session_for_mobile

  devise_for :admins
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" } 

  get "brands/index" => "brands#index", as: :brands_index
  devise_for :brands, controllers: { registrations: "brands/registrations", sessions: "brands/sessions" }, path_prefix: "my"
  resources :brands

  get 'categories/index' => "categories#index", as: :categories_index
  get 'categories/show/:id' => "categories#show", as: :category_show
  post 'categories/create' => "categories#create", as: :category_create
  post 'categories/update' => "categories#update", as: :category_update
  get 'categories/destroy/:id' => "categories#destroy", as: :category_destroy

  post 'sub_categories/create' => "sub_categories#create", as: :sub_categories_create
  post 'sub_categories/update' => "sub_categories#update", as: :sub_categories_update
  get 'sub_categories/destroy/:id' => "sub_categories#destroy", as: :sub_categories_destroy

  get "cities/index" => "cities#index", as: :cities_index
  get 'cities/show/:id' => "cities#show", as: :cities_show
  post 'cities/create' => "cities#create", as: :cities_create
  post 'cities/update' => "cities#update", as: :cities_update
  get 'cities/destroy/:id' => "cities#destroy", as: :cities_destroy
  post 'cities/search_districts_for_city' => "cities#search_districts_for_city", as: :search_districts_for_city

  post 'districts/create' => "districts#create", as: :districts_create
  post 'districts/update' => "districts#update", as: :districts_update
  get 'districts/destroy/:id' => "districts#destroy", as: :districts_destroy

  get 'coupons/history' => "coupons#history", as: :coupons_history
  get 'coupons/published_coupons/:id' => "coupons#published_coupons", as: :coupons_published
  get 'coupons/category/:id' => "coupons#by_category", as: :coupons_by_category
  get 'coupons/sub_category/:id' => "coupons#by_sub_category", as: :coupons_by_sub_category
  get 'coupons/saved_coupons/:id' => "coupons#saved_coupons", as: :saved_coupons
  get 'coupons/pending_coupons/:id' => "coupons#pending_coupons_by_brand", as: :pending_coupons_by_brand
  get 'coupons/pending_coupons' => "coupons#pending_coupons", as: :pending_coupons
  get 'coupons/valid_coupons' => "coupons#valid_coupons", as: :valid_coupons
  get 'coupons/favorites' => "coupons#favorites", as: :favorite_coupons
  post 'coupons/mark_favorite' => "coupons#mark_favorite", as: :mark_favorite
  post 'coupons/approve_coupon/:id' => "coupons#approve_coupon", as: :approve_coupon
  resources :coupons

  get "coupon_states/index" => "coupon_states#index", as: :coupon_states_index
  post "coupon_states/create" => "coupon_states#create", as: :coupon_states_create
  get "coupon_states/destroy/:id" => "coupon_states#destroy", as: :coupon_states_destroy
  post "coupon_states/update" => "coupon_states#update", as: :coupon_states_update

  get "coupon_types/index" => "coupon_types#index", as: :coupon_types_index
  post "coupon_types/create" => "coupon_types#create", as: :coupon_types_create
  get "coupon_types/destroy/:id" => "coupon_types#destroy", as: :coupon_types_destroy
  post "coupon_types/update" => "coupon_types#update", as: :coupon_types_update

  get "branches/index/:id" => "branches#index", as: :branches_index
  post "branches/create" => "branches#create", as: :create_branch
  get "branches/destroy/:id" => "branches#destroy", as: :destroy_branch
  post "branches/edit" => "branches#edit", as: :edit_branch
  post "branches/grouped_branches" => "branches#grouped_branches", as: :grouped_branches
  post "branches/branches_in_district" => "branches#branches_in_district"

  

end

app/models/category.rb
class Category < ActiveRecord::Base

	has_many :sub_categories

	def self.brands_by_category(category_id)
		category = Category.find(category_id)
		brands = []
		category.sub_categories.each do |sub_cat|
			sub_cat.brands.each do |brand|
				brands << brand
			end
		end
		brands.uniq!
	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	def index
		@categories = Category.all
		respond_to do |format|
			format.html
			format.json
		end
	end

	def show
		@category = Category.find(params[:id])
		@subcategories = @category.sub_categories
		respond_to do |format|
		  format.js
  		end
	end

	def create
		@category = Category.new
		@category.name = params[:name]
		@category.save
		respond_to do |format|
			format.js
		end
	end

	def update
		@category = Category.find(params[:cat_id])
		@category.name = params[:new_name]
		@category.save
		respond_to do |format|
			format.js
		end
	end

	def destroy
		@category = Category.find(params[:id]).destroy()
		respond_to do |format|
			format.js
		end
	end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category_list_item.html.haml
#category_group.accordion-group
	.accordion-heading
		=link_to "#cat_#{cat.id}", class: "accordion-toggle", data: {toggle: "collapse", parent: "#accordion3", id: "#{cat.id}"} do
			=cat.name.capitalize
	.accordion-body.collapse{ id: "cat_#{cat.id}"}
		.accordion-inner
			%ul
				%li
					=link_to "Mostrar", category_show_path(cat.id), remote: true
				%li
					=link_to "Editar", "#update_category_form", role: "button", data: {toggle: "modal"}
				%li
					=link_to "Eliminar", category_destroy_path(cat.id), remote: true, class: "destroy_link", data: { confirm: "Una vez eliminado no podra recuperarse. Está seguro de continuar?"}

app/views/categories/_sub_category_list_item.html.haml
-if uncomplete == true
	%tr
		%td
			=index
		%td
			=sb.name
		%td
			=link_to "Editar", "#update_sub_category_form", class: "up_sub_cat", role: "button", data: {toggle: "modal", id: "#{sb.id}"}
		%td
			= link_to "Eliminar", sub_categories_destroy_path(sb.id), remote: true, class: "destroy_sb"
-else
	%h1
		= subcategories.first.category.name.upcase
	%table.table.table-striped
		%tr
			%th
				\#
			%th
				Nombre
			%th{colspan: "2"}
				Opciones
		- subcategories.each.with_index(1) do |sb, index|
			%tr
				%td
					=index
				%td
					=sb.name
				%td
					Editar
				%td
					=link_to "Eliminar", sub_categories_destroy_path(sb.id), remote: true, class: "destroy_sb",  data: { confirm: "Una vez eliminado no podra recuperarse. Está seguro de continuar?"}

app/views/categories/_subcategory_list.html.haml
#subcategory_content{class: @category.name.tr(" ", "_")}
	%h1
		= category.name.upcase
	- unless subcategories.empty?
		%table.table.table-striped
			%tr
				%th
					\#
				%th
					Nombre
				%th{colspan: "2"}
					Opciones
			- subcategories.each.with_index(1) do |sb, index|
				= render "sub_category_list_item", sb: sb, index: index, uncomplete: true

=link_to "Crear sub-categoria", "#new_sub_category_form", class: "btn btn-warning", role: "button", data: {toggle: "modal"}

=form_tag sub_categories_create_path, remote: true do
	#new_sub_category_form.modal.hide.fade{tabindex: "-1", role: "dialog", aria:{ labelledby: "myModalLabel", hidden: "true"}}
		.modal-header
			%button.close{ id: "close_button", type: "button", data: {dismiss: "modal"}, aria: {hidden: "true"}}
				×
			%h3
				Nueva Subcategoria
		.modal-body
			=hidden_field_tag :category_id, category.id
			.new_category_part
				=label_tag :name, "Categoria: "
				=text_field_tag :name
		.modal-footer
			%button#close_button.btn{data: {dismiss: "modal"}, aria: {hidden: "true"}}
				Cancelar
			=submit_tag "Guardar", class: "btn btn-primary"

=form_tag sub_categories_update_path, remote: true do
	#update_sub_category_form.modal.hide.fade{tabindex: "-1", role: "dialog", aria:{ labelledby: "myModalLabel", hidden: "true"}}
		.modal-header
			%button.close{ id: "close_button", type: "button", data: {dismiss: "modal"}, aria: {hidden: "true"}}
				×
			%h3
				Editar subcategoria
		.modal-body
			= hidden_field_tag :sub_cat_id, value: 0
			.new_category_part
				=label_tag :new_sub_name, "Nuevo nombre: "
				=text_field_tag :new_sub_name
		.modal-footer
			%button#sub_cat_close_button.btn{data: {dismiss: "modal"}, aria: {hidden: "true"}}
				Cancelar
			=submit_tag "Guardar", class: "btn btn-primary"

app/views/categories/create.js.haml
$("#accordion3").append("#{j render 'category_list_item', cat: @category}");
$("#category_close_button").click();

app/views/categories/destroy.js.haml
$(".toDestroy").parents(".accordion-group").remove();
- html_node = ".#{@category.name}"
if($("#{html_node}").html().length > 0){$("#subcategory_total_content").html(" ");}

app/views/categories/index.html.haml
.page_container
	%h6
		%a{href: "index.html"}
			home
		\/ categorias
	.inner_content
		.row
			.span3
				%h4 Categorias
				#accordion3.accordion
					- @categories.each do |cat|
						= render "category_list_item", cat: cat
				=link_to "Crear categoria", "#new_category_form", class: "btn btn-warning", role: "button", data: {toggle: "modal"}
			#subcategory_total_content.span9
				%h1
					Listar categorias
				%p
					%b
						Elige una opción en la izquierda para mostrar las subcategorias

=form_tag category_create_path, remote: true do
	#new_category_form.modal.hide.fade{tabindex: "-1", role: "dialog", aria:{ labelledby: "myModalLabel", hidden: "true"}}
		.modal-header
			%button.close{ id: "category_close_button", type: "button", data: {dismiss: "modal"}, aria: {hidden: "true"}}
				×
			%h3
				Editar categoria
		.modal-body
			.new_category_part
				=label_tag :name, "Categoria: "
				=text_field_tag :name
		.modal-footer
			%button#close_button.btn{data: {dismiss: "modal"}, aria: {hidden: "true"}}
				Cancelar
			=submit_tag "Guardar", class: "btn btn-primary"

=form_tag category_update_path, remote: true do
	#update_category_form.modal.hide.fade{tabindex: "-1", role: "dialog", aria:{ labelledby: "myModalLabel", hidden: "true"}}
		.modal-header
			%button.close{ id: "update_category_close_button", type: "button", data: {dismiss: "modal"}, aria: {hidden: "true"}}
				×
			%h3
				Nueva Categoria
		.modal-body
			=hidden_field_tag :cat_id, value: -1
			.new_category_part
				=label_tag :new_name, "Categoria: "
				=text_field_tag :new_name
		.modal-footer
			%button#close_button.btn{data: {dismiss: "modal"}, aria: {hidden: "true"}}
				Cancelar
			=submit_tag "Guardar", class: "btn btn-primary"

app/views/categories/show.js.haml
$("#subcategory_total_content").html("#{j render "subcategory_list", category: @category, subcategories: @subcategories}");

app/views/categories/update.js.haml
$(".accordion-toggle[data-id=#{@category.id}]").parents(".accordion-group").replaceWith("#{j render 'category_list_item', cat: @category}");
$("#update_category_close_button").click();